# Generated by Django 5.0.7 on 2024-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
