# Generated by Django 5.0.7 on 2024-07-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=20)),
                ('topics', models.TextField()),
                ('course_room', models.CharField(max_length=20)),
                ('teacher_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_code', to='teacher.teacher')),
            ],
        ),
    ]
