# Generated by Django 5.0.7 on 2024-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=28)),
                ('code', models.PositiveSmallIntegerField()),
                ('username', models.CharField(max_length=27)),
                ('Student_class', models.CharField(max_length=20)),
                ('Student_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
